# Indexação Temporal e Inspeção Inicial

O que a gente quer fazer: importar o dataset.csv e dar uma olhada nele (ver as colunas, quantos registros tem, se falta dado, etc). Esse notebook mostra o código que a gente usou no primeiro encontro sobre como organizar dados de tempo no Pandas. Pra saber mais, olha o README.md.

In [ ]:
import pandas as pd
from pathlib import Path

pd.set_option('display.max_columns', None)

(1): Importando o dataset. Pra o Pandas entender que é um dado de tempo, a gente precisa fazer duas coisas: mudar a coluna de data pra datetime64 e fazer dessa coluna o índice do DataFrame. A coluna de data no nosso dataset se chama Data.

In [ ]:
DATA_PATH = Path('..') / 'data' / 'raw' / 'dataset.csv'
COLUNA_DATA = 'Data'

df = pd.read_csv(
    DATA_PATH,
    parse_dates=[COLUNA_DATA],
    index_col=COLUNA_DATA
)

df = df.sort_index()

df.head()

            Trocas_Oleo  Manutencao_Motor
Data
2024-01-01         11.0               2.0
2024-01-02          9.0               4.0
2024-01-03         12.0               1.0
2024-01-04         15.0               8.0
2024-01-05         25.0              10.0

In [ ]:
type(df.index)

pandas.DatetimeIndex

(2): Inspeção inicial. A gente vai olhar as colunas, os tipos de dados e quantos registros tem.

In [ ]:
df.head()

            Trocas_Oleo  Manutencao_Motor
Data
2024-01-01         11.0               2.0
2024-01-02          9.0               4.0
2024-01-03         12.0               1.0
2024-01-04         15.0               8.0
2024-01-05         25.0              10.0

In [ ]:
df.tail()

            Trocas_Oleo  Manutencao_Motor
Data
2025-12-27         44.0              18.0
2025-12-28         45.0              20.0
2025-12-29         27.0              12.0
2025-12-30         27.0              10.0
2025-12-31         30.0               9.0

In [ ]:
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 731 entries, 2024-01-01 to 2025-12-31
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Trocas_Oleo       725 non-null    float64
 1   Manutencao_Motor  728 non-null    float64
dtypes: float64(2)
memory usage: 17.1 KB

In [ ]:
print(f'Quantidade de registros: {df.shape[0]}')
print(f'Quantidade de atributos: {df.shape[1]}')

Quantidade de registros: 731
Quantidade de atributos: 2

In [ ]:
df.columns.tolist()

['Trocas_Oleo', 'Manutencao_Motor']

In [ ]:
df.describe()

       Trocas_Oleo  Manutencao_Motor
count   725.000000        728.000000
mean     26.020690         10.179945
std      11.620655          5.419338
min       0.000000         -2.000000
25%      18.000000          7.000000
50%      26.000000         10.000000
75%      33.000000         13.000000
max     150.000000         85.000000

In [ ]:
print(f'Início da série: {df.index.min()}')
print(f'Fim da série: {df.index.max()}')

Início da série: 2024-01-01 00:00:00
Fim da série: 2025-12-31 00:00:00

In [ ]:
print('Valores nulos por coluna:')
print(df.isnull().sum())
print(f'\nDatas duplicadas no índice: {df.index.duplicated().sum()}')

Valores nulos por coluna:
Trocas_Oleo         6
Manutencao_Motor    3
dtype: int64

Datas duplicadas no índice: 0

(3): Olhando os números (que a gente achou no describe()). A gente viu umas coisas meio estranhas no describe() e vai dar uma olhada. Não vamos arrumar agora, só anotar.

In [ ]:
df[df['Manutencao_Motor'] < 0]

            Trocas_Oleo  Manutencao_Motor
Data
2024-09-03          6.0              -2.0
2024-09-04          5.0              -1.0
2024-09-11          2.0              -1.0
2024-09-17          4.0              -2.0
2024-09-19          0.0              -1.0

In [ ]:
df[df['Trocas_Oleo'] > 75]

            Trocas_Oleo  Manutencao_Motor
Data
2024-02-15        150.0               4.0